development:
  adapter: postgresql
  encoding: utf8
  database: hard_todo_development
  pool: 20
  username: deploy
  password: dabakh
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: hard_todo_test
  pool: 20
  username: deploy
  password: dabakh
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: hard_todo_production
  pool: 20
  username: deploy
  password: dabakh
  host: localhost